//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.05 at 01:36:35 AM ART 
//


package org.example.carpintero_severino;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cowherdIds" type="{http://www.example.org/carpintero_severino}CowHerdIds"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cowherdIds"
})
@XmlRootElement(name = "addCowToHerdRequest")
public class AddCowToHerdRequest {

    @XmlElement(required = true)
    protected CowHerdIds cowherdIds;

    /**
     * Gets the value of the cowherdIds property.
     * 
     * @return
     *     possible object is
     *     {@link CowHerdIds }
     *     
     */
    public CowHerdIds getCowherdIds() {
        return cowherdIds;
    }

    /**
     * Sets the value of the cowherdIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CowHerdIds }
     *     
     */
    public void setCowherdIds(CowHerdIds value) {
        this.cowherdIds = value;
    }

}
