//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.05 at 01:36:35 AM ART 
//


package org.example.carpintero_severino;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CowHerdIds complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CowHerdIds">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cow_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="herd_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CowHerdIds", propOrder = {
    "cowId",
    "herdId"
})
public class CowHerdIds {

    @XmlElement(name = "cow_id")
    protected int cowId;
    @XmlElement(name = "herd_id")
    protected int herdId;

    /**
     * Gets the value of the cowId property.
     * 
     */
    public int getCowId() {
        return cowId;
    }

    /**
     * Sets the value of the cowId property.
     * 
     */
    public void setCowId(int value) {
        this.cowId = value;
    }

    /**
     * Gets the value of the herdId property.
     * 
     */
    public int getHerdId() {
        return herdId;
    }

    /**
     * Sets the value of the herdId property.
     * 
     */
    public void setHerdId(int value) {
        this.herdId = value;
    }

}
