//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.05 at 01:36:35 AM ART 
//


package org.example.carpintero_severino;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.carpintero_severino package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddCowToHerdResponse_QNAME = new QName("http://www.example.org/carpintero_severino", "addCowToHerdResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.carpintero_severino
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateHerdRequest }
     * 
     */
    public CreateHerdRequest createCreateHerdRequest() {
        return new CreateHerdRequest();
    }

    /**
     * Create an instance of {@link Herd }
     * 
     */
    public Herd createHerd() {
        return new Herd();
    }

    /**
     * Create an instance of {@link CreateCowRequest }
     * 
     */
    public CreateCowRequest createCreateCowRequest() {
        return new CreateCowRequest();
    }

    /**
     * Create an instance of {@link Cow }
     * 
     */
    public Cow createCow() {
        return new Cow();
    }

    /**
     * Create an instance of {@link GetCowInfoRequest }
     * 
     */
    public GetCowInfoRequest createGetCowInfoRequest() {
        return new GetCowInfoRequest();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link CreateCowResponse }
     * 
     */
    public CreateCowResponse createCreateCowResponse() {
        return new CreateCowResponse();
    }

    /**
     * Create an instance of {@link GetHerdInfoRequest }
     * 
     */
    public GetHerdInfoRequest createGetHerdInfoRequest() {
        return new GetHerdInfoRequest();
    }

    /**
     * Create an instance of {@link CreateCowBCSResponse }
     * 
     */
    public CreateCowBCSResponse createCreateCowBCSResponse() {
        return new CreateCowBCSResponse();
    }

    /**
     * Create an instance of {@link CowBCS }
     * 
     */
    public CowBCS createCowBCS() {
        return new CowBCS();
    }

    /**
     * Create an instance of {@link AddCowToHerdRequest }
     * 
     */
    public AddCowToHerdRequest createAddCowToHerdRequest() {
        return new AddCowToHerdRequest();
    }

    /**
     * Create an instance of {@link CowHerdIds }
     * 
     */
    public CowHerdIds createCowHerdIds() {
        return new CowHerdIds();
    }

    /**
     * Create an instance of {@link CreateCowBCSRequest }
     * 
     */
    public CreateCowBCSRequest createCreateCowBCSRequest() {
        return new CreateCowBCSRequest();
    }

    /**
     * Create an instance of {@link CreateHerdResponse }
     * 
     */
    public CreateHerdResponse createCreateHerdResponse() {
        return new CreateHerdResponse();
    }

    /**
     * Create an instance of {@link GetHerdInfoResponse }
     * 
     */
    public GetHerdInfoResponse createGetHerdInfoResponse() {
        return new GetHerdInfoResponse();
    }

    /**
     * Create an instance of {@link HerdInfo }
     * 
     */
    public HerdInfo createHerdInfo() {
        return new HerdInfo();
    }

    /**
     * Create an instance of {@link GetCowInfoResponse }
     * 
     */
    public GetCowInfoResponse createGetCowInfoResponse() {
        return new GetCowInfoResponse();
    }

    /**
     * Create an instance of {@link CowInfo }
     * 
     */
    public CowInfo createCowInfo() {
        return new CowInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/carpintero_severino", name = "addCowToHerdResponse")
    public JAXBElement<Boolean> createAddCowToHerdResponse(Boolean value) {
        return new JAXBElement<Boolean>(_AddCowToHerdResponse_QNAME, Boolean.class, null, value);
    }

}
