//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.18 at 03:52:12 PM ART 
//


package com.servicios.DTO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CowInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CowInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cow" type="{http://www.example.org/carpintero_severino}Cow"/>
 *         &lt;element name="bsc" type="{http://www.example.org/carpintero_severino}CowBCS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CowInfo", propOrder = {
    "cow",
    "bsc"
})
public class CowInfo {

    @XmlElement(required = true)
    protected Cow cow;
    protected CowBCS bsc;

    /**
     * Gets the value of the cow property.
     * 
     * @return
     *     possible object is
     *     {@link Cow }
     *     
     */
    public Cow getCow() {
        return cow;
    }

    /**
     * Sets the value of the cow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cow }
     *     
     */
    public void setCow(Cow value) {
        this.cow = value;
    }

    /**
     * Gets the value of the bsc property.
     * 
     * @return
     *     possible object is
     *     {@link CowBCS }
     *     
     */
    public CowBCS getBsc() {
        return bsc;
    }

    /**
     * Sets the value of the bsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link CowBCS }
     *     
     */
    public void setBsc(CowBCS value) {
        this.bsc = value;
    }

}
