//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.18 at 03:52:12 PM ART 
//


package com.servicios.DAO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cowInfo" type="{http://www.example.org/carpintero_severino}CowInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cowInfo"
})
@XmlRootElement(name = "getCowInfoResponse")
public class GetCowInfoResponse {

    @XmlElement(required = true)
    protected CowInfo cowInfo;

    /**
     * Gets the value of the cowInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CowInfo }
     *     
     */
    public CowInfo getCowInfo() {
        return cowInfo;
    }

    /**
     * Sets the value of the cowInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CowInfo }
     *     
     */
    public void setCowInfo(CowInfo value) {
        this.cowInfo = value;
    }

}
